<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');
class Notification extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Notification_model');
        $this->load->library('form_validation');
    }
    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'notification/index?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'notification/index?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'notification/index';
            $config['first_url'] = base_url() . 'notification/index';
        }
        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Notification_model->total_rows($q);
        $notification = $this->Notification_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'notification_data' => $notification,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('notification/notification_list', $data);
    }

/* End of file Notification.php */
/* Location: ./application/controllers/Notification.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-01 03:50:20 */
/* http://harviacode.com */